### ISSUE TITLE
ornabook 第3317列後面資料無法叫出來

### ISSUE THREAD

**Issue by w12wwww** [IamSkyBlue/TC_orna_bot#23]
Ornabook 
第3317列後面的資料無法用 ~search 叫出來
請修正 
謝謝

**Comment by w12wwww** [comment]
更新
剛剛把末尾的寵物區資料共179列
順序變動移到法術區資料之前
再做測試，結果全部正常 
沒有3317列之後的問題

**Comment by IamSkyBlue** [comment]
![螢幕擷取畫面 2022-12-21 105558](https://user-images.githubusercontent.com/34653812/208809934-65770249-4b95-4dc0-895b-7c8000ee1a38.jpg)
試了3318以及最底部資料皆為正常
如果可以再請您提供遇到此問題的條目，或是其他重現方法
非常感謝!
